services:
  db:
    image: postgres:17
    container_name: image_server_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: images_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: image_server_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  app:
    build: .
    container_name: image_server_app
    restart: unless-stopped
    volumes:
      - images:/app/images
      - logs:/app/logs

    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=images_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - TEMPLATES_PATH=templates
      - IMAGES_PATH=images
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: image_server_nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      - "80:80"
    restart: unless-stopped

volumes:
  images:
  logs:
  db_data:
